--http://www.editorialox.com/municipiosvenezuela.htm



INSERT INTO sc.municipio (municipio,idesta)
VALUES
--Distrito Capital
('Libertador (Caracas)',10),
--Estado Amazonas
('Alto Orinoco (La Esmeralda)',1),
('Atabapo (San Fernando de Atabapo)',1),
('Atures (Puerto Ayacucho)',1),
('Autana (Isla Ratón)',1),
('Manapiare (San Juan de Manapiare)',1),
('Maroa (Maroa)',1),
('Río Negro (San Carlos de Río Negro)',1),
--Estado Anzoátegui
('Anaco (Anaco)',2),
('Aragua (Aragua de Barcelona)',2),
('Bolívar (Barcelona)',2),
('Bruzual (Clarines)',2),
('Cajigal (Onoto)',2),
('Carvajal (Valle de Guanape)',2),
('Diego Bautista Urbaneja (Lechería)',2),
('Freites (Cantaura)',2),
('Guanipa (San José de Guanipa)',2),
('Guanta (Guanta)',2),
('Independencia (Soledad)',2),
('Libertad (San Mateo)',2),
('McGregor (El Chaparro)',2),
('Miranda (Pariaguán)',2),
('Monagas (San Diego de Cabrutica)',2),
('Peñalver (Puerto Píritu)',2),
('Píritu (Píritu)',2),
('San Juan de Capistrano (Boca de Uchire)',2),
('Santa Ana (Santa Ana)',2),
('Simón Rodriguez (El Tigre)',2),
('Sotillo (Puerto La Cruz)',2),
--Estado Apure
('Achaguas (Achaguas)',3),
('Biruaca (Biruaca)',3),
('Muñoz (Bruzual)',3),
('Páez (Guasdualito)',3),
('Pedro Camejo (San Juan de Payara)',3),
('Rómulo Gallegos (Elorza)',3),
('San Fernando (San Fernando de Apure)',3),
--Estado Aragua
('Bolívar (San Mateo)',4),
('Camatagua(Camatagua)',4),
('Francisco Linares Alcántara (Santa Rita)',4),
('Girardot (Maracay)',4),
('José Ángel Lamas (Santa Cruz)',4),
('José Félix Ribas (La Victoria)',4),
('José Rafael Revenga (El Consejo)',4),
('Libertador (Palo Negro)',4),
('Mario Briceño Iragorry (El Limón)',4),
('Ocumare de la Costa de Oro (Ocumare de la Costa)',4),
('San Casimiro (San Casimiro)',4),
('San Sebastián (San Sebastián de los Reyes)',4),
('Santiago Mariño (Turmero)',4),
('Santos Michelena (Las Tejerías)',4),
('Sucre (Cagua)',4),
('Tovar (Colonia Tovar)',4),
('Urdaneta (Barbacoas)',4),
('Zamora (Villa de Cura)',4),
--Estado Barinas
('Alberto Arvelo Torrealba (Sabaneta)',5),
('Andrés Eloy Blanco (El Cantón)',5),
('Antonio José de Sucre (Socopó)',5),
('Arismendi (Arismendi)',5),
('Barinas (Barinas)',5),
('Bolívar (Barinitas)',5),
('Cruz Paredes (Barrancas)',5),
('Ezequiel Zamora (Santa Bárbara)',5),
('Obispos (Obispos)',5),
('Pedraza (Ciudad Bolivia)',5),
('Rojas (Libertad)',5),
('Sosa (Ciudad de Nutrias)',5),
--Estado Bolívar
('Caroní (Ciudad Guayana)',6),
('Cedeño (Caicara del Orinoco)',6),
('El Callao (El Callao)',6),
('Gran Sabana (Santa Elena de Uairén)',6),
('Heres (Ciudad Bolívar)',6),
('Piar (Upata)',6),
('Raúl Leoni (Ciudad Piar)',6),
('Roscio (Guasipati)',6),
('Sifontes (Tumeremo)',6),
('Sucre (Maripa)',6),
('Padre Pedro Chen (El Palmar)',6),
--Estado Carabobo
('Bejuma (Bejuma)',7),
('Carlos Arvelo (Güigüe)',7),
('Diego Ibarra (Mariara)',7),
('Guacara (Guacara)',7),
('Juan José Mora (Morón)',7),
('Libertador (Tocuyito)',7),
('Los Guayos (Los Guayos)',7),
('Miranda (Miranda)',7),
('Montalbán (Montalbán)',7),
('Naguanagua (Naguanagua)',7),
('Puerto Cabello (Puerto Cabello)',7),
('San Diego (San Diego)',7),
('San Joaquín (San Joaquín)',7),
('Valencia (Valencia)',7),
--Estado Cojedes
('Anzoátegui (Cojedes)',8),
('Falcón (Tinaquillo)',8),
('Girardot (El Baúl)',8),
('Lima Blanco (Macapo)',8),
('Pao de San Juan Bautista (El Pao)',8),
('Ricaurte (Libertad)',8),
('Rómulo Gallegos',8),
--Estado Delta Amacuro
('Antonio Díaz Curiapo (Curiapo)',9),
('Casacoima (Sierra Imataca)',9),
('Pedernales (Pedernales)',9),
('Tucupita (Tucupita)',9),
--Estado Falcón
('Acosta (San Juan de los Cayos)',11),
('Bolívar (San Luis)',11),
('Buchivacoa (Capatárida)',11),
('Cacique Manaure (Yaracal)',11),
('Carirubana (Punto Fijo)',11),
('Colina (La Vela de Coro)',11),
('Dabajuro (Dabajuro)',11),
('Democracia (Pedregal)',11),
('Falcón (Pueblo Nuevo)',11),
('Federación (Churuguara)',11),
('Jacura (Jacura)',11),
('Los Taques (Santa Cruz de Los Taques)',11),
('Mauroa (Mene de Mauroa)',11),
('Miranda (Santa Ana de Coro)',11),
('Monseñor Iturriza (Chichiriviche)',11),
('Palmasola (Palmasola)',11),
('Petit (Cabure)',11),
('Píritu (Píritu)',11),
('San Francisco (Mirimire)',11),
('Silva (Tucacas)',11),
('Sucre (La Cruz de Taratara)',11),
('Tocópero (Tocópero)',11),
('Unión (Santa Cruz de Bucaral)',11),
('Urumaco (Urumaco)',11),
('Zamora (Puerto Cumarebo)',11),
--Estado Guarico
('Esteros de Camaguan(Camaguan)',12),
('Chaguaramas(Chaguaramas)',12),
('El Socorro (El Socorro)',12),
('Francisco de Miranda (Calabozo)',12),
('José Félix Ribas (Tucupido)',12),
('José Tadeo Monagas (Altagracia de Orituco)',12),
('Juan Germán Roscio (San Juan de Los Morros',12),
('Julián Mellado (El Sombrero)',12),
('Las Mercedes (Las Mercedes)',12),
('Leonardo Infante (Valle de La Pascua)',12),
('Pedro Zaraza (Zaraza)',12),
('Ortíz (Ortíz)',12),
('San Gerónimo de Guayabal (Guayabal)',12),
('San José de Guaribe (San José de Guaribe)',12),
('Santa María de Ipire (Santa María de Ipire)',12),
--Estado Lara
('Andrés Eloy Blanco (Sanare)',13),
('Crespo (Duaca)',13),
('Iribarren (Barquisimeto)',13),
('Jiménez (Quibor)',13),
('Morán (El Tocuyo)',13),
('Palavecino (Cabudare)',13),
('Simón Planas (Sarare)',13),
('Torres (Carora)',13),
('Urdaneta (Siquisique)',13),
--Estado Merida
('Alberto Adriani (El Vigía)',14),
('Andrés Bello (La Azulita)',14),
('Antonio Pinto Salinas (Santa Cruz de Mora)',14),
('Sucre (Lagunillas)',14),
('Tovar (Tovar)',14),
('Tulio Febres Cordero (Nueva Bolivia)',14),
('Zea (Zea)',14),
--Estado Miranda
('Acevedo (Caucagua)',15),
('Andrés Bello (San José de Barlovento)',15),
('Baruta (Baruta)',15),
('Brión (Higuerote)',15),
('Buroz (Mamporal)',15),
('Carrizal (Carrizal)',15),
('Chacao (Chacao)',15),
('Cristóbal Rojas (Charallave)',15),
('El Hatillo (El Hatillo)',15),
('Guaicaipuro (Los Teques)',15),
('Independencia (Santa Teresa del Tuy)',15),
('Lander (Ocumare del Tuy)',15),
('Los Salias (San Antonio de los Altos)',15),
('Páez (Río Chico)',15),
('Paz Castillo (Santa Lucía)',15),
('Pedro Gual (Cúpira)',15),
('Plaza (Guarenas)',15),
('Simón Bolívar (San Francisco de Yare)',15),
('Sucre (Petare)',15),
('Urdaneta (Cúa)',15),
('Zamora (Guatire)',15),
--Estado Monagas
('Acosta (San Antonio de Capayacuar)',16),
('Aguasay (Aguasai)',16),
('Bolívar',16),
('Cedeño (Caicara)',16),
('Ezequiel Zamora (Punta de Mata)',16),
('Libertador (Temblador)',16),
('Maturín (Maturín)',16),
('Piar (Aragua)',16),
('Punceres (Quiriquire)',16),
('Santa Bárbara (Santa Bárbara)',16),
('Sotillo (Barrancas del Orinco)',16),
('Uracoa (Uracoa)',16),
--Estado Nueva Esparta
('Antolín del Campo (La Plaza de Paraguachí)',17),
('Arismendi (La Asunción)',17),
('Díaz (San Juan Bautista)',17),
('García (El Valle del Espíritu Santo)',17),
('Gómez (Santa Ana)',17),
('Maneiro (Pampatar)',17),
('Marcano (Juan Griego)',17),
('Mariño (Porlamar)',17),
('Península de Macanao (Boca de Río)',17),
('Tubores (Punta de Piedras)',17),
('Villalba (San Pedro de Coche)',17),
--Estado Portuguesa
('Agua Blanca (Agua Blanca)',18),
('Araure (Araure)',18),
('Esteller (Píritu)',18),
('Guanare (Guanare)',18),
('Guanarito (Guanarito)',18),
('Monseñor José Vicenti de Unda (Chabasquén de Unda)',18),
('Ospino (Ospino)',18),
('Páez (Acarigua)',18),
('Papelón (Papelón)',18),
('San Genaro de Boconoíto (Boconoíto)',18),
('San Rafael de Onoto (San Rafael de Onoto)',18),
('Santa Rosalía (El Playón)',18),
('Sucre (Biscucuy)',18),
('Turén (Villa Bruzual)',18),
--Estado Sucre
('Andrés Eloy Blanco (Casanay)',19),
('Andrés Mata (San José de Aerocuar)',19),
('Arismendi (Río Caribe)',19),
('Benítez (El Pilar)',19),
('Bermúdez (Carúpano)',19),
('Bolívar (Marigüitar)',19),
('Cajigal (Yaguaraparo)',19),
('Cruz Salmerón Acosta (Araya)',19),
('Libertador (Tunapuy)',19),
('Mariño (Irapa)',19),
('Mejía (San Antonio del Golfo)',19),
('Montes (Cumanacoa)',19),
('Ribero (Cariaco)',19),
('Sucre (Cumaná)',19),
('Valdez (Güiria)',19),
--Estado Tachira
('Andrés Bello(Cordero)',20),
('Antonio Rómulo Costa (Las Mesas)',20),
('Ayacucho (El Colón)',20),
('Bolívar (San Antonio del Táchira)',20),
('Cárdenas (Táriba)',20),
('Córdoba (Santa Ana de Táchira)',20),
('Fernández Feo (San Rafael del Piñal)',20),
('Francisco de Miranda (San José de Bolívar)',20),
('García de Hevia (La Fría)',20),
('Guásimos (Palmira)',20),
('Independencia (Capacho Nuevo)',20),
('Jáuregui (La Grita)',20),
('José María Vargas (El Cobre)',20),
('Junín (Rubio)',20),
('San Judas Tadeo (Umuquena)',20),
('Libertad (Capacho Viejo)',20),
('Libertador (Abejales)',20),
('Lobatera (Lobatera)',20),
('Michelena (Michelena)',20),
('Panamericano (Coloncito)',20),
('Pedro María Ureña (Ureña)',20),
('Rafael Urdaneta (Delicias)',20),
('Samuel Dario Maldonado (La Tendida)',20),
('San Cristóbal (San Cristóbal)',20),
('Seboruco (Seboruco)',20),
('Simón Rodríguez (San Simon)',20),
('Sucre (Queniquea)',20),
('Torbes (San Josesito)',20),
('Uribante (Pregonero)',20),
--Estado Trujillo
('Andrés Bello (Santa Isabel)',21),
('Boconó (Boconó)',21),
('Bolívar (Sabana Grande)',21),
('Candelaria (Chejendé)',21),
('Carache (Carache)',21),
('Escuque (Escuque)',21),
('José Felipe Márquez Cañizalez (El Paradero)',21),
('Juan Vicente Campos Elías (Campo Elías)',21),
('La Ceiba (Santa Apolonia)',21),
('Miranda (El Dividive)',21),
('Pampán (Pampán)',21),
('Trujillo (Trujillo)',21),
('Andres Linares (San Lazaro)',21),
('Pampanito (Pampanito)',21),
--Estado Vargas
('Vargas (La Guaira)',22),
--Estado Yaracuy
('Arístides Bastidas (San Pablo)',23),
('Bolívar (Aroa)',23),
('Bruzual (Chivacoa)',23),
('Cocorote (Cocorote)',23),
('Independencia (Independencia)',23),
--Estado Zulia
('Almirante Padilla (El Toro)',24),
('Baralt (San Timoteo)',24),
('Cabimas (Cabimas)',24),
('Catatumbo (Encontrados)',24),
('Colón (San Carlos del Zulia)',24),
('Francisco Javier Pulgar (Pueblo Nuevo-El Chivo)',24),
('Jesús Enrique Losada (La Concepción)',24),
('Jesús María Semprún (Casigua El Cubo)',24)
