--Reiniciar la tabla y con ello el auto incremental / sequence ELIMINANDO LOS REGISTROS
TRUNCATE TABLE sc.estado RESTART IDENTITY CASCADE

-- reiniciar conteo para crear los roles y permisos
TRUNCATE TABLE public.auth_assignment RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.auth_item RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.auth_item_child RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.auth_rule RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.usuario RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.estado RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.municipio RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.parroquia RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.asistencia RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.direcuser RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.equipo RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.estudiante RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.fcarga RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.fgeneral RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.fpantalla RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.fsoftware RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.ftarjetamadre RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.fteclado RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.formato RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.imagen RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.insteduc RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.libros RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.multimedia RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.niveleduc RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.proyecto RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.realaum RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.representante RESTART IDENTITY CASCADE;
TRUNCATE TABLE sc.sedeciat RESTART IDENTITY CASCADE;

-- FORZAR TIPO DE DATO
ALTER TABLE sc.equipo
ALTER COLUMN entregado
TYPE integer USING CAST(entregado AS character varying);

--Reiniciar auto incremental / sequence sin eliminar la tabla
ALTER SEQUENCE campo_id_seq RESTART WITH 1

-- AÑADIR LLAVES PRIMARIAS
ALTER TABLE ONLY sc.auditoria
ADD CONSTRAINT idaudi
PRIMARY KEY(idaudi);

-- AÑADIR LLAVES FORANEAS
ALTER TABLE ONLY sc.insteduc
ADD CONSTRAINT idrgesta
FOREIGN KEY (idrgesta) REFERENCES sc.regestado(idrgesta);

-- AÑADIR COLUMNA
ALTER TABLE sc.estudiante ADD COLUMN iduser integer;
